const projects = [
  {number:'01', category:'PEOPLE & OPERATIONS', title:'AIMS HRMS', subtitle:'Attendance, without the admin overload.', summary:'An internal HR and attendance system built around the realities of employee operations.', tags:'HRMS · Attendance · Reporting', type:'attendance', detail:'A centralized space for employees and administrators to manage attendance, schedules, and records. Built around actual operational requirements, from daily punch records to department-level reporting.', features:['Employee and administrator authentication','Attendance and punch record management','Department and shift-based scheduling','Automatic late-arrival detection','Attendance import and reporting','Employee dashboards and administrative controls'], flow:['Punch records','Attendance rules','HR reporting']},
  {number:'02',category:'BUSINESS APPLICATION',title:'Payroll & Employee Management',subtitle:'A clearer path from records to payroll.',summary:'Bringing employee records and attendance-related payroll workflows into one structured application.',tags:'Employee records · Payroll workflows',type:'payroll',detail:'Recurring payroll administration becomes difficult when employee information and attendance data live across separate files. This application brings those records and internal payroll workflows into a centralized system.',features:['Centralized employee records','Attendance-related payroll data','Organized internal payroll workflows','A shared application for recurring administrative work'],flow:['Employee data','Payroll workflow','Management review']},
  {number:'03',category:'AUTOMATION & EXPLORATION',title:'Retail Operations & Surveillance',subtitle:'Connecting the everyday across locations.',summary:'Operational logs, store activity reporting, and automated workflows for multi-location retail.',tags:'Retail operations · Automation · AI exploration',type:'retail',detail:'Tools shaped by the daily requirements of multi-location retail operations: recording store activity, coordinating opening and closing workflows, and making reporting more consistent. AI-assisted surveillance and event detection remain areas of experimentation.',features:['Automated operational reporting','Store activity and operational logs','Store opening and closing workflows','Surveillance workflow support','Experiments with AI-assisted event detection'],flow:['Store activity','Operational logs','Reporting']},
  {number:'04',category:'DATA & BUSINESS INTELLIGENCE',title:'Management & Reporting Dashboards',subtitle:'From store-level data to the bigger picture.',summary:'Web and Power BI dashboards that help make operational and sales performance easier to understand.',tags:'Power BI · KPIs · Data analysis',type:'analytics',detail:'Dashboards for exploring operational and sales performance across retail locations, with store-level data, filters, regional comparisons, and summaries designed for management.',features:['Store-level operational and sales data','Key performance indicators','Reporting filters','Regional comparisons','Management summaries','Web dashboards and Power BI reporting'],flow:['Store data','KPIs & comparisons','Management insight']}
];
function preview(type) {
  if(type === 'attendance') return '<div class="mini-head">AIMS / Attendance <span>Overview</span></div><div class="mini-stats"><div>Present<strong>128</strong></div><div>On leave<strong>06</strong></div><div>Late arrivals<strong>03</strong></div></div><div class="mini-row"><b>Employee</b><b>Check-in</b><b>Status</b></div><div class="mini-row"><span>Team member A</span><span>08:57 AM</span><i>On time</i></div><div class="mini-row"><span>Team member B</span><span>08:59 AM</span><i>On time</i></div>';
  if(type === 'payroll') return '<div class="mini-head">Payroll workspace <span>Monthly cycle</span></div><div class="mini-stats"><div>Records reviewed<strong>42 / 56</strong></div><div>Cycle status<strong>In review</strong></div></div><div class="mini-track"><span></span></div><div class="mini-row"><b>Employee records</b><span>Reviewed</span><i>✓ Complete</i></div><div class="mini-row"><b>Attendance data</b><span>Processing</span><i>In progress</i></div>';
  if(type === 'retail') return '<div class="mini-head">Operations / Activity log <span>Multi-location</span></div><div class="mini-log">09:00 · Store opening <span>Recorded</span></div><div class="mini-log">09:12 · Daily checklist <span>Completed</span></div><div class="mini-log">10:30 · Activity report <span>Generated</span></div><div class="mini-log">11:45 · Management summary <span>Ready</span></div>';
  return '<div class="mini-head">Performance overview <span>Regional comparison</span></div><div class="bar-chart" aria-hidden="true">'+[38,58,47,75,62,90,80,100,87,110].map(n=>'<span style="height:'+n+'%"></span>').join('')+'</div><div class="mini-row"><span>Central</span><span>North</span><span>South</span></div>';
}
document.getElementById('project-grid').innerHTML = projects.map((p,i)=>`<article class="project"><div class="project-art" aria-hidden="true"><span class="preview-label">Interface concept · illustrative data</span><div class="mini-window">${preview(p.type)}</div></div><div class="project-info"><div class="project-meta"><span>${p.category}</span><span>${p.number}</span></div><h3>${p.title}</h3><p>${p.summary}</p><div class="project-footer"><span class="project-tags">${p.tags}</span><button class="project-open" data-project="${i}">View project<span class="sr-only">: ${p.title}</span></button></div></div></article>`).join('');
const dialog = document.getElementById('project-dialog');
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{
 const p=projects[Number(button.dataset.project)];
 document.getElementById('dialog-content').innerHTML=`<p class="dialog-kicker">PROJECT ${p.number} / ${p.category}</p><h2 class="dialog-title" id="dialog-title">${p.title}</h2><p>${p.subtitle}</p><p class="dialog-text">${p.detail}</p><h3 class="dialog-section-label">Scope & capabilities</h3><ul class="dialog-features">${p.features.map(f=>`<li>${f}</li>`).join('')}</ul><h3 class="dialog-section-label">Conceptual workflow</h3><div class="diagram">${p.flow.map(f=>`<span>${f}</span>`).join('<i>→</i>')}</div><p class="dialog-note">The portfolio preview illustrates the workflow; it is not a live application or production screenshot.</p><a class="button primary dialog-link" href="https://www.linkedin.com/in/syed-mujtaba-aly-b8bb28392/" target="_blank" rel="noopener noreferrer">Discuss this project</a>`;
 dialog.showModal();
 document.body.style.overflow='hidden';
}));
dialog.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
dialog.addEventListener('close',()=>document.body.style.overflow='');
document.getElementById('year').textContent=new Date().getFullYear();
const runButton=document.getElementById('run-flow');
runButton.addEventListener('click',async()=>{
 runButton.disabled=true;
 const nodes=[...document.querySelectorAll('.flow-node')];
 const labels=['Capturing…','Automating…','Summarizing…'];
 for(let i=0;i<nodes.length;i++){
   nodes.forEach((n,j)=>n.classList.toggle('active',i===j));runButton.textContent=labels[i];
   await new Promise(resolve=>setTimeout(resolve,650));
 }
 runButton.textContent='Workflow complete ✓';document.getElementById('flow-status').textContent='Illustrative workflow complete: data captured, rules applied, insights ready.';
 await new Promise(resolve=>setTimeout(resolve,1200));
 runButton.innerHTML='Run workflow <span>▶</span>';runButton.disabled=false;
});
